# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Angular deploy
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1
        with:
          github_access_token: ${{ secrets.NG_DEPLOY_REPO_ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
          build_configuration: production # The build environment for the app. please look configurations in your angular.json
          base_href: /jsonlogic-examiner/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages # The branch the action should deploy to.
          angular_dist_build_folder: dist/jsonlogic-examiner # The folder where your project is supposed to be after running ng build by the action.

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Angular Deploy gh-pages is cool!


